"use strict";
var pessoa;
(function (pessoa) {
    let p = new pessoa.Paciente();
    p.setnome("Bogotá");
    p.setcpf("101.101.101-01");
    p.setcodPaciente(1);
    let p1 = new pessoa.Paciente();
    p1.setnome("M'Baku");
    p1.setcpf("202.202.202-02");
    p1.setcodPaciente(2);
    let p2 = new pessoa.Paciente();
    p2.setnome("Mickael");
    p2.setcpf("303.303.303-03");
    p2.setcodPaciente(3);
    let e = new pessoa.Enfermeiro();
    e.setnome("Dandara");
    e.setcpf("112.112.112-12");
    e.setcodFuncionario(1);
    e.setcoren(11);
    let e1 = new pessoa.Enfermeiro();
    e1.setnome("Gabriela");
    e1.setcpf("223.522.223-23");
    e1.setcodFuncionario(3);
    e1.setcoren(12);
    let e2 = new pessoa.Enfermeiro();
    e2.setnome("Nycolas");
    e2.setcpf("334.633.337-33");
    e2.setcodFuncionario(3);
    e2.setcoren(13);
    let m = new pessoa.Medico();
    m.setnome("Taniax");
    m.setespecialidade("Anestesista");
    m.setcrm(123);
    m.setcpf("123.123.123-11");
    m.setcodFuncionario(21);
    let m1 = new pessoa.Medico();
    m1.setnome("KauanElBrabo");
    m1.setespecialidade("Ortopedista");
    m1.setcrm(456);
    m1.setcpf("123.123.123-12");
    m1.setcodFuncionario(22);
    let m2 = new pessoa.Medico();
    m2.setnome("Jesus");
    m2.setespecialidade("Cirurgião");
    m2.setcrm(789);
    m2.setcpf("123.123.123-13");
    m2.setcodFuncionario(23);
    let h = new pessoa.Hospital();
    h.setnome("Hospitar");
    h.addEnfermeiros(e);
    h.addEnfermeiros(e1);
    h.addEnfermeiros(e2);
    h.addMedicos(m);
    h.addMedicos(m1);
    h.addMedicos(m2);
    h.addPacientes(p);
    h.addPacientes(p1);
    h.addPacientes(p2);
    document.getElementById("hospital").textContent = h.getnome();
    let tbMedico = document.getElementById("tbMedico");
    h.getmedicos().forEach(h => {
        let nome = h.getnome();
        let cpf = h.getcpf();
        let crm = h.getcrm();
        let especialidade = h.getespecialidade();
        let html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + crm + "</td><td>" + especialidade + "</td></tr>";
        tbMedico.innerHTML += html;
    });
    let tbEnfermeiras = document.getElementById("tbEnfermeiras");
    h.getEnfermeiros().forEach(h => {
        let nome = h.getnome();
        let cpf = h.getcpf();
        let corem = h.getcoren();
        let html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + corem + "</td></tr>";
        tbEnfermeiras.innerHTML += html;
    });
    let tbPacientes = document.getElementById("tbPacientes");
    h.getpacientes().forEach(h => {
        let nome = h.getnome();
        let cpf = h.getcpf();
        let cod = h.getcodPaciente();
        let html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + cod + "</td></tr>";
        tbPacientes.innerHTML += html;
    });
})(pessoa || (pessoa = {}));
