"use strict";
var pessoa;
(function (pessoa) {
    var p = new pessoa.Paciente();
    p.setNome("Boris");
    p.setCpf("001.001.001-01");
    p.setCodPaciente(1);
    var p1 = new pessoa.Paciente();
    p1.setNome("Filipe");
    p1.setCpf("002.002.002-02");
    p1.setCodPaciente(2);
    var p2 = new Pessoa.Paciente();
    p2.setNome("Pipo");
    p2.setCpf("003.003.003-03");
    p2.setCodPaciente(3);
    var e = new Pessoa.Enfermeiro();
    e.setNome("Daiane");
    e.setCpf("111.111.111-11");
    e.setCodFuncionario(1);
    e.setCoren(11);
    var e1 = new Pessoa.Enfermeiro();
    e1.setNome("Fernanda");
    e1.setCpf("222.222.222-22");
    e1.setCodFuncionario(3);
    e1.setCoren(12);
    var e2 = new Pessoa.Enfermeiro();
    e2.setNome("Gabriela");
    e2.setCpf("333.333.333-33");
    e2.setCodFuncionario(3);
    e2.setCoren(13);
    var m = new Pessoa.Medico();
    m.setNome("Pica Pau");
    m.setEspecialidade("Operações");
    m.setCrm(123);
    m.setCpf("123.123.123-11");
    m.setCodFuncionario(21);
    var m1 = new Pessoa.Medico();
    m1.setNome("Pernalonga");
    m1.setEspecialidade("Ortopedista");
    m1.setCrm(456);
    m1.setCpf("123.123.123-12");
    m1.setCodFuncionario(22);
    var m2 = new Pessoa.Medico();
    m2.setNome("Pateta");
    m2.setEspecialidade("Pediatra");
    m2.setCrm(789);
    m2.setCpf("123.123.123-13");
    m2.setCodFuncionario(23);
    var h = new Pessoa.Hospital();
    h.setNome("Santa Casa de Misericórdia");
    h.addEnfermeiros(e);
    h.addEnfermeiros(e1);
    h.addEnfermeiros(e2);
    h.addMedicos(m);
    h.addMedicos(m1);
    h.addMedicos(m2);
    h.addPacientes(p);
    h.addPacientes(p1);
    h.addPacientes(p2);
    document.getElementById("hospital").textContent = h.Getnome();
    var tbMedico = document.getElementById("tbMedico");
    h.getMedicos().forEach(function (h) {
        var nome = h.getNome();
        var cpf = h.getCpf();
        var crm = h.getCrm();
        var especialidade = h.getEspecialidade();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + crm + "</td><td>" + especialidade + "</td></tr>";
        tbMedico.innerHTML += html;
    });
    var tbEnfermeiras = document.getElementById("tbEnfermeiras");
    h.getEnfermeiros().forEach(function (h) {
        var nome = h.getNome();
        var cpf = h.getCpf();
        var corem = h.getCoren();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + corem + "</td></tr>";
        tbEnfermeiras.innerHTML += html;
    });
    var tbPacientes = document.getElementById("tbPacientes");
    h.getPacientes().forEach(function (h) {
        var nome = h.getNome();
        var cpf = h.getCpf();
        var cod = h.getCodPaciente();
        var html = "<tr><td>" + nome + "</td><td>" + cpf + "</td><td>" + cod + "</td></tr>";
        tbPacientes.innerHTML += html;
    });
})(pessoa || (pessoa = {}));